### ISSUE TITLE
Move install part of this repository to a build system

### ISSUE THREAD

**Issue by Mic92** [dezgeg/nix-fpm-multiuser#3]
It would be cool, if in addition to fpm packaging the repository would also allow distro maintainers
to have a simple autotools-like workflow to create native packages. Then we would have the same code running on all non-nixos distributions. `apt install nix` sounds still less scarier to most people then curling scripts into a shell.
Maybe it could be also renamed to `nix-multiuser` to make it more general.

**Comment by Mic92** [comment]
Current upstream approaches: 
- https://packages.gentoo.org/packages/sys-apps/nix
- https://aur.archlinux.org/packages/nix-multiuser

Note that both packages package nix instead with the native package manager.

**Comment by Mic92** [comment]
Maybe also @asppsa and @trofi would be interesting in joining this discussion.

**Comment by Mic92** [comment]
I don't think downloading and installing packages from build server is good user experience vs. using the native package manager. Also the history shows that nix upstream is very slow when it comes to incorporating fixes for non-nixos packaging so it is likely to break again.

**Comment by dezgeg** [comment]
> I don't think downloading and installing packages from build server is good user experience vs. using the native package manager. 

I agree on that, but I believe getting Nix into (at least some of) package repositories is rather a political problem, not technical one due to us using `/nix` and not adhering to FHS. I don't remember any links/pointers to the discussion but my understanding is this has historically been a blocker for getting included in Debian.

> Also the history shows that nix upstream is very slow when it comes to incorporating fixes for non-nixos packaging so it is likely to break again.

That's exactly why I've chosen a total rewrite and different approach than how the current Nix .deb / .rpm builds work; with fpm the entire https://github.com/NixOS/nix/blob/master/nix.spec.in file becomes unnecessary, these sorts of Debian-specific lines as in https://github.com/NixOS/nix/blob/master/release.nix#L344 become unnecessary, and on top we gain pacman support. I'm very hopeful that with good integration tests (I'm thinking of launching stock EC2/cloud images of various distros in kvm, with cloud-init providing the portable mechanism of getting root access over ssh) these packages won't regress for existing distro releases.

**Comment by Mic92** [comment]
I don't think this will be a problem in other distribution beside debian. And if we hit some debian maintainers on a good day, we might even convince them (I think that discussion was just a lack of understanding).

**Comment by Mic92** [comment]
If you go the nix upstream road, I think it would be good if you still make a separate project under the nixos org instead of the nix repository, so we don't just have to rely on core maintainers having time to fix things. There is no particular reason this has to live in the same source tree as nix in my opinion.

**Comment by dezgeg** [comment]
Besides our usage of the non-FHS path `/nix`, I expect many of them will object to not compiling against their system libraries, e.g. this Fedora policy on bundling dependencies in the package: https://fedoraproject.org/wiki/Bundled_Libraries?rd=Packaging:Bundled_Libraries

**Comment by Mic92** [comment]
Ok. I thought the nix binary is not part of the binary.

**Comment by Mic92** [comment]
If it would be a packing hook/pure shell script or so, there should be no objections from the distro sides.

**Comment by asppsa** [comment]
FWIW, my `nix-multiuser` AUR package is now defunct, as the main [nix][1] package now does most of what is needed (i.e. build users).  I have switched my focus to a stand-alone script (still very preliminary) that can be used to install/update nix directly from the official binaries, and can also setup build users and sandoxing.  If you're interested, you can check it out [here][2].

[1]: https://aur.archlinux.org/packages/nix/
[2]: https://github.com/asppsa/archlinux-nix

**Comment by Mic92** [comment]
The official nix installer script also supports multi-user now btw.

**Comment by Mic92** [comment]
@asppsa maybe you can drop a link here to help other archlinux users to install nix: https://nixos.wiki/wiki/Install_Nix_in_multi-user_mode_on_non-NixOS

**Comment by therealpxc** [comment]
Can we get SRPMs from `fpm` this way? If we produce RPMs properly built with `.spec` files, it is trivial to create a repo that builds Nix for any RPM distro, e.g., with the [Open Build Service](http://openbuildservice.org/), and distro maintainers could use our RPM as a basis for something they'd like to include in their own distros.

`fpm`-generated RPMs will probably not pass linting or work with other tooling for any RPM-based distro. If we go this route, distro maintainers who'd like to submit Nix RPMs to their distro, they'll probably have to start from scratch.

And btw, some time long after that discussion on the Debian mailing list, there is a [new effort](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=877331) to get Nix added to the official Debian repositories. You can [see the work in progress here on GitHub](https://github.com/KaiHa/nix-debian).

If we want to ensure that Nix is readily available for as many users of Debian-based distributions as possible, finding out what we can do to help @KaiHa might be our best bet.

**Comment by dezgeg** [comment]
No, this approach only packages the prebuilt Nix closure inside a directory in a RPM. I don't really know too much of what sRPMs do but maybe the competing approach https://github.com/NixOS/nix/pull/1141 can be used for that. 

> fpm-generated RPMs will probably not [...] work with other tooling for any RPM-based distro. 

What sort of tooling do you mean? I am not at all experienced with RPM (I basically only know how to run `rpm -i *.rpm` and `rpm -e nix` to test this thing on OpenSUSE, CentOS and Fedora Core).

> If we go this route, distro maintainers who'd like to submit Nix RPMs to their distro, they'll probably have to start from scratch.

Well, the whole idea/point of this experiment was to (eventually have) Hydra build a single RPM that works on any RPM distro with systemd (and currently, doesn't have SELinux enabled) by not using anything else from the distro besides `/bin/sh`, basic shell commands like `useradd` and the `systemctl` command available. So by definition the steps of rebuilding the RPM wouldn't be required by the downstream distro packager, just uploading it to their distro's equivalent of PPA or AUR.

**Comment by therealpxc** [comment]
The way that packages are uploaded to repositories for most distributions is source-based, so that the package gets built with distro tooling after. This is [true of Ubuntu PPAs](https://help.launchpad.net/Packaging/PPA/Uploading) and of [repositories of all kinds on openSUSE's instance of the Open Build Service](https://en.opensuse.org/openSUSE:Packaging_guidelines#No_inclusion_of_pre-built_binaries_or_libraries), for example.

There are ways to make repos that can be used by most distros that just provide binary packages, but for most distros those are outside of the usual mechanisms for creating community/user repositories. AUR is exceptional because it has no standards/requirements for packages.

I think there is still value in trying to get Nix included in upstream distros, and to make it possible for distro maintainers and power users to package, build, and distribute Nix using the tools that are typical in their communities.

However, this:

> Well, the whole idea/point of this experiment was to (eventually have) Hydra build a single RPM that works on any RPM distro with systemd (and currently, doesn't have SELinux enabled) by not using anything else from the distro besides /bin/sh, basic shell commands like useradd and the systemctl command available.

still sounds awesome. And if we have to host our own repos somewhere that gets updated by dumping RPMs into a directory and running `createrepo`, we'd still be making Nix a hell of a lot easier (or at least more comfortable) for many users.

I definitely don't want to discourage you in this effort. I just think that other approaches may also still prove useful in bringing Nix to people. And I think we'll probably want to set up repos to distribute these RPMs and DEBs, if we can. But we don't know if or how those efforts will pan out; it's easy to see why you started this one.

I'll try to come back to this after work and see if I can figure out how to be useful instead of just fretting. :-)

**Comment by dezgeg** [comment]
> The way that packages are uploaded to repositories for most distributions is source-based, so that the package gets built with distro tooling after.

Yes, that clearly is the intended usage of those services. But what actually enforces that the end result is built from source code? E.g. the "source" tarball of the Steam package in multiverse (https://launchpad.net/ubuntu/+source/steam/1:1.0.0.54+repack-5ubuntu1) just contains a prebuilt `steam` executable in binary form, presumably extracted from Steam's own binary release. (Now that's apparently not a PPA but something different, but presumably the same reasoning applies to this PPA I've used in the past that installs the Oracle's proprietary JRE).

> I definitely don't want to discourage you in this effort. I just think that other approaches may also still prove useful in bringing Nix to people. 

No worries, I didn't interpret it that way. I fully understand that doing things the distro-approved way has its benefits and that the distros have their no-library-bundling policies for a reason.

E.g. from the point of an enterprise distro like SuSE, it clearly has a benefit to them that if say, a Glibc vulnerability is published, they only have to implement and publish the fix in one place and not hunt through all of their thousands of packages for additional bundled Glibcs to fix. But, in the case of Nix, the user has probably installed Nix for the sole purpose of installing or building other packages from Nixpkgs. So when the hypothetical Glibc vulnerability comes, it's most likely pretty inconsequential whether their Nix package itself is built against the SuSE glibc or not, because they need to get the fixed glibc for Nixpkgs-sourced packages from `nixos.org` anyway; having the SuSE-patched glibc will not help with those in any case. So at least for that specific case, to me spending the effort to package Nix against the distro libraries doesn't give the same amount returns as packaging other kinds of software.

Another thing which just came to my mind is that new versions of Nixpkgs start to depend on new features of Nix quite soon, so any distro packages need to keep up with the default version of Nix in the latest NixOS release with quite a rapid pace. This enough sounds like it could block Nix from usefully being included in many of the slower-moving distros' default repositories.

> And if we have to host our own repos somewhere that gets updated by dumping RPMs into a directory and running createrepo.

Do you happen to know how compatible such repos are between RPM-using distros and how often backwards-incompatible changes happen to `createrepo`? If it could be show that it's pretty much maintenance-free (as in, write a script once and except to have it keep running unchanged for maybe 5 years at a time) I would imagine the `createrepo` part's something that conceivably could be hosted on `nixos.org` as well.

**Comment by Mic92** [comment]
I added travis support to upload binary packages to github: https://github.com/Mic92/nix-fpm-multiuser/releases

**Comment by alexvorobiev** [comment]
I cloned the repo and tried building the rpm. It failed:
```
hash mismatch in fixed-output derivation '/nix/store/v9ildlkshrfqwxz8kixcm7izkwbsmhf9-fpm-c126785':
  wanted: sha256:15mz86jzywqs51q3s3fv6i14b0sy7apj45aafymksp1zy0y7gggv
  got:    sha256:1p8cx284i2zfyd54awankxgazp6gyrqjwq1imvb030m9qnbkxf1s
building '/nix/store/3q5p5yarv11c9r9g6ja2wzbdgm7a10bn-gemfile-and-lockfile.drv'...
cannot build derivation '/nix/store/79d9sspfm1pvahapb0v3p5ysm2r4bfs4-ruby2.6.5-fpm-1.10.0.drv': 1 dependencies couldn't be built
cannot build derivation '/nix/store/vxncbv3as4n932cvwjjw5hc9dfz1hky2-fpm-1.10.0.drv': 1 dependencies couldn't be built
building '/nix/store/pvmi7wmn6l1dd9jwc9s4mcj99kkxzwqb-nix-tarball-2.2pre6572_7e617e7.drv'...
cannot build derivation '/nix/store/sccz2l11cid3cx9n9nsbhygkd9pbrm0r-nix-fpm-multiuser.drv': 1 dependencies couldn't be built
error: build of '/nix/store/sccz2l11cid3cx9n9nsbhygkd9pbrm0r-nix-fpm-multiuser.drv' failed
```
